"""added balance column to the debt table

Revision ID: 1555c22627ca
Revises: 66e374927b10
Create Date: 2019-12-30 00:53:31.782040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1555c22627ca'
down_revision = '66e374927b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debt', sa.Column('balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debt', 'balance')
    # ### end Alembic commands ###
