"""created the first db migration

Revision ID: 5b547c4962e4
Revises: 
Create Date: 2019-12-27 00:06:03.680112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b547c4962e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=40), nullable=False),
    sa.Column('date_supplied', sa.DateTime(), nullable=True),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('cleared', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debt')
    # ### end Alembic commands ###
