"""added the debt amount field  to the db

Revision ID: 66e374927b10
Revises: 5b547c4962e4
Create Date: 2019-12-27 00:13:27.408846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e374927b10'
down_revision = '5b547c4962e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debt', sa.Column('debt_amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debt', 'debt_amount')
    # ### end Alembic commands ###
